### ISSUE TITLE
Latest versions are confused

### ISSUE THREAD

**Issue by aydoganemsiz** [yagizhanNY/SiemensIXBlazor#13]
Hi, the web application cannot be started with the latest update. 
The following versions are confused. 

- Microsoft.AspNetCore.Components.WebAssembly: 7.0.13
- Microsoft.AspNetCore.Components.WebAssembly.DevServer: 7.0.13
- SiemensIXBlazor: 0.4.2

Can you check please.

**Comment by yagizhanNY** [comment]
Hi @aydoganemsiz, could you share your dotnet version and Visual Studio version?

**Comment by aydoganemsiz** [comment]
Ofcourse, 
.NET 7 and VS 2022.

**Comment by yagizhanNY** [comment]
I mean version details. You can see the detailed version of dotnet with `dotnet --version` command. You can find detailed version info of Visual Studio from `Help -> About Microsoft Visual Studio` tab.

**Comment by aydoganemsiz** [comment]
> I mean version details. You can see the detailed version of dotnet with `dotnet --version` command. You can find detailed version info of Visual Studio from `Help -> About Microsoft Visual Studio` tab.

.NET Version: 7.0.400
VS 2022 Version: 17.7.3 (VisualStudio.17.Release/17.7.3+34024.191)

**Comment by aydoganemsiz** [comment]
> Please update your `dotnet` version to `7.0.403` and Visual Studio version to `17.7.6`.
> 
> In the next release (`0.4.3`) we will update our dependencies to `7.0.13`

![2023-10-30 08_24_57-DevTools - localhost_7118_aggridpreview](https://github.com/yagizhanNY/SiemensIXBlazor/assets/39672099/939813d7-1a58-4621-b31f-a950472f8f8e)

Hi,
I tested it with the versions you suggested.
The project was started but AG Grid did not work and gave the attached error.

**Comment by yagizhanNY** [comment]
Looks like the error is coming from `Tabs` component. Could you open a new issue about it?
