### ISSUE TITLE
Icon button size

### ISSUE THREAD

**Issue by VolkerLieber** [yagizhanNY/SiemensIXBlazor#22]
The documentation defines a size property for icon buttons: [(https://ix.siemens.io/docs/controls/button/#properties-ix-icon-button)](https://ix.siemens.io/docs/controls/button/#properties-ix-icon-button)

The two possible ways, I could think of are:

```
  public enum IconButtonSize
  {
      _12 = 12,
      _16 = 16,
      _24 = 24
  }
```

and

```
/// <value>
///  12 | 16 | 24, default: 24
/// </value>
[Parameter]
public int Size { get; set; } = 24;
```

What would you prefer or do you know a better way?

**Comment by yagizhanNY** [comment]
Hello @VolkerLieber, if it's possible we should always go with enums. In my opinion this is much more readable. Thanks for contribution!
