### ISSUE TITLE
IconButton Size issue

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/SiemensIXBlazor#24]
![image](https://github.com/yagizhanNY/SiemensIXBlazor/assets/41087670/72ec63c0-b9df-43bf-bfba-17f18e4cfae4)

We have an issue about button size attribute of `IconButton` component. We have to fix the enum. Size attribute value is wrong in the HTML element.

@VolkerLieber #23

**Comment by VolkerLieber** [comment]
@yagizhanNY Yes, it seems that I forgot to convert the enum correctly. Thanks for noticing
