### ISSUE TITLE
Update ReadME

### ISSUE THREAD

**Issue by asheesh1996** [yagizhanNY/SiemensIXBlazor#26]
Hi @yagizhanNY ,

Great work and I want to use the component library for my .NET8 based blazor project, can you update the documentation on how to use it

**Comment by VolkerLieber** [comment]
The readme should be up to date in that regard. Can you please describe your problem with the current readme?

**Comment by yagizhanNY** [comment]
Hi @asheesh1996, actually noting changes with .NET8. Installation process is same. But it would be good to add supported .NET version in README 👍

**Comment by yagizhanNY** [comment]
Is it still ongoing issue for you? @asheesh1996

**Comment by yagizhanNY** [comment]
If it's still ongoing please re-open the issue.
