### ISSUE TITLE
Implement Card component

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/SiemensIXBlazor#36]
https://ix.siemens.io/docs/controls/card/

![image](https://github.com/yagizhanNY/SiemensIXBlazor/assets/41087670/56f11b1f-7d83-41aa-a87b-200409840236)

**Comment by emncnozge** [comment]
I want to implement this component.

**Comment by yagizhanNY** [comment]
Please don't forget to add this component into README file too. @emncnozge

**Comment by yagizhanNY** [comment]
implemented with #39 PR
